### ISSUE TITLE
Issue on the aux loss

### ISSUE THREAD

**Issue by longspringcity** [Tsingularity/FRN#3]
Thanks for your work. 
I print the L1 L2 variable in the auxrank() function of frn_train.py and find that the last half elements are 0. Is this consistent with the Auxiliary Loss in the paper (i and j belong to different categories).

**Comment by daviswer** [comment]
Thanks for catching this! The code is correct, but not strictly consistent with the paper. Since we are computing symmetric dot products as our pairwise distance function, we iterate through all the combinations rather than all the permutations of pairs. This is the same as [29] in the paper, which is the original source for this loss. 

However, we set the length of L1 and L2 as if we were doing the permutations, as implied by equation 11 in the paper. So when we fill in the actual distances, half appear to be missing. We'll fix things to make clearer what's actually going on. 

That said, computing pairwise permutations/combinations amounts to a simple doubling/halving of the other auxiliary loss value. We found that this loss has very little impact in practice, and scaling it one way or the other shouldn't change performance meaningfully.

**Comment by daviswer** [comment]
Code is fixed, new results incoming

**Comment by longspringcity** [comment]
Thank you for your comprehensive reply. Have a nice day!

**Comment by daviswer** [comment]
Thanks, you too! I ran 8 corrected models (4 FRN models from this repo, and 4 baselines from the paper, spanning datasets and backbone architectures) and all are within 1pp of published performance, without being consistently better or worse. FRN models were particularly unaffected (within .5pp in all cases). So I'm going to go ahead and say that this bug didn't affect the results significantly. Thanks again for pointing it out to us.
