### ISSUE TITLE
RuntimeError: inverse_cuda: For batch 0: U(2,2) is zero, singular U.

### ISSUE THREAD

**Issue by SoonFa** [Tsingularity/FRN#6]
Great work!

We meet an issue caused by the computation of [inverse_cuda](https://github.com/Tsingularity/FRN/blob/main/models/FRN.py#L77) We have pasted the error information as shown below,
```shell
m_inv = (sts+torch.eye(sts.size(-1)).to(sts.device).unsqueeze(0).mul(lam)).inverse() # way, d, d
RuntimeError: inverse_cuda: For batch 0: U(2,2) is zero, singular U.
```
May I repalce `inverse()` with`cholesky_inverse()`?

**Comment by Tsingularity** [comment]
Looks like someone else also came across the same error: https://github.com/Tsingularity/FRN/issues/4#issuecomment-903588885

I think this seems to be an issue due to pytorch's version difference. Could u please try using our provided conda environment and re-run the code again? https://github.com/Tsingularity/FRN#code-environment This is the environment I used to develop this codebase and I never came across this runtime error before. Just let me know if this doesn't work for u.

For replacing inverse() with cholesky_inverse(), personally, I never used this function before so I cannot guarantee anything to be honest lol. But feel free to take a try and see how it goes.

Feel free to let us know if there's anything else we can help with.

**Comment by daviswer** [comment]
Seconding that this is likely the same pytorch version issue. 

Unfortunately, replacing inverse() with cholesky_inverse() isn't straightforward, as (to my knowledge) cholesky_inverse() doesn't currently support batched inputs, and implementing this sequentially could cause significant slowdowns.

**Comment by Tsingularity** [comment]
closing this for now. feel free to re-open it if you need more help.

**Comment by victolee0** [comment]
I have same issue.

when I follow your *readme.md*,  I got this error.
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mars/anaconda3/envs/FRN/lib/python3.7/site-packages/torch/__init__.py", line 189, in <module>
    _load_global_deps()
  File "/home/mars/anaconda3/envs/FRN/lib/python3.7/site-packages/torch/__init__.py", line 142, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/mars/anaconda3/envs/FRN/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/mars/anaconda3/envs/FRN/lib/python3.7/site-packages/torch/lib/../../../../libcublas.so.11: undefined symbol: free_gemm_select, version libcublasLt.so.11
`

so i found the method solving this problem here (https://github.com/pytorch/pytorch/issues/51080)

and then, i get this problem

`Traceback (most recent call last):
  File "train.py", line 34, in <module>
    tm.train(model)
  File "../../../../trainers/trainer.py", line 181, in train
    iter_counter=iter_counter)
  File "../../../../trainers/frn_train.py", line 101, in pre_train
    log_prediction = model.forward_pretrain(inp)
  File "../../../../models/FRN.py", line 137, in forward_pretrain
    recon_dist = self.get_recon_dist(query=feature_map,support=self.cat_mat,alpha=alpha,beta=beta) # way*query_shot*resolution, way
  File "../../../../models/FRN.py", line 77, in get_recon_dist
    m_inv = (sts+torch.eye(sts.size(-1)).to(sts.device).unsqueeze(0).mul(lam)).inverse() # way, d, d
RuntimeError: inverse_cuda: For batch 7: U(6,6) is zero, singular U.
`

I think your ```environment.yml``` does not working well now.
Can you check this?

Sorry for my bad English.
Thank you.
